# Generated by Django 5.2.7 on 2025-11-04 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eclstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cigaroffer',
            name='cigar',
        ),
        migrations.DeleteModel(
            name='Cocktail',
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='Liquor',
        ),
        migrations.DeleteModel(
            name='Offering',
        ),
        migrations.DeleteModel(
            name='Cigar',
        ),
        migrations.DeleteModel(
            name='CigarOffer',
        ),
    ]
