# Generated by Django 5.2.7 on 2025-11-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclstore', '0002_remove_cigaroffer_cigar_delete_cocktail_delete_drink_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this banner'),
        ),
        migrations.AddField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first'),
        ),
    ]
