# Generated by Django 5.2.7 on 2025-11-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclstore', '0003_alter_banner_options_banner_is_active_banner_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cigar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cigars/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CigarOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name or title of the offer', max_length=200)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage (e.g., 10 for 10%)', max_digits=5)),
                ('apply_to_all', models.BooleanField(default=False, help_text='If true, this offer applies to all cigars')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('cigars', models.ManyToManyField(blank=True, related_name='offer_list', to='eclstore.cigar')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
