# Generated by Django 5.2.7 on 2025-11-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclstore', '0004_cigar_cigaroffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cigar',
            name='image',
        ),
        migrations.AlterField(
            model_name='cigar',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this cigar'),
        ),
        migrations.AlterField(
            model_name='cigar',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
