# Generated by Django 5.2.7 on 2025-11-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclstore', '0005_remove_cigar_image_alter_cigar_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('bar', 'Bar'), ('cocktail', 'Cocktail')], default='bar', max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DrinkOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage (e.g., 15 for 15%)', max_digits=5)),
                ('apply_to_all', models.BooleanField(default=False, help_text='Apply to all drinks')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('drinks', models.ManyToManyField(blank=True, related_name='offers', to='eclstore.drink')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
