# Generated by Django 5.2.7 on 2025-11-05 01:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclstore', '0006_drink_drinkoffer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drink',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Drink', 'verbose_name_plural': 'Drinks'},
        ),
        migrations.AddField(
            model_name='drink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='category',
            field=models.CharField(choices=[('bar', 'Bar'), ('cocktail', 'Cocktail')], max_length=20),
        ),
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='drink',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls the display order in the list.'),
        ),
        migrations.DeleteModel(
            name='DrinkOffer',
        ),
    ]
