# Generated by Django 5.2.7 on 2025-11-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclstore', '0007_alter_drink_options_drink_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('whiskey', 'Whiskey'), ('rum', 'Rum'), ('vodka', 'Vodka'), ('gin', 'Gin'), ('tequila', 'Tequila'), ('wine', 'Wine'), ('other', 'Other')], max_length=30)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Liquor',
                'verbose_name_plural': 'Liquors',
                'ordering': ['order', 'name'],
            },
        ),
    ]
