# Generated by Django 5.2.7 on 2025-11-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclstore', '0010_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='badge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_link',
            field=models.CharField(blank=True, choices=[('', '— No Link —'), ('/', 'Home'), ('/cigars/', 'Cigar Collection'), ('/bar/', 'Bar & Cocktails'), ('/liquor/', 'Liquor Collection'), ('/events/', 'Events'), ('/contact/', 'Contact'), ('/about/', 'About Us')], default='', help_text='Select which section this banner should link to.', max_length=100),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='tagline',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
