# Generated by Django 5.2.7 on 2025-11-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclstore', '0011_alter_banner_badge_alter_banner_button_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['order'], 'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of display on homepage'),
        ),
    ]
