# Generated by Django 5.2.7 on 2025-11-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclstore', '0012_alter_banner_options_alter_banner_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='button_link',
            field=models.CharField(blank=True, choices=[('', '— No Link —'), ('/', 'Home'), ('/cigars/', 'Cigar Collection'), ('/bar/', 'Bar & Cocktails'), ('/liquor/', 'Liquor Collection'), ('/event_page/', 'Events'), ('/contact/', 'Contact'), ('/about/', 'About Us')], default='', help_text='Select which section this banner should link to.', max_length=100),
        ),
    ]
