# Generated by Django 5.2.7 on 2025-11-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclstore', '0014_alter_banner_button_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('event_type', models.CharField(choices=[('private', 'Private Event'), ('corporate', 'Corporate Gathering'), ('birthday', 'Birthday Celebration'), ('other', 'Other')], default='private', max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('guests', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
