# Generated by Django 5.2.7 on 2025-11-11 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eclstore', '0015_eventbooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventbooking',
            old_name='date',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='eventbooking',
            old_name='guests',
            new_name='guest_count',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='time',
        ),
    ]
