# Generated by Django 5.2.7 on 2025-11-11 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eclstore', '0016_rename_date_eventbooking_event_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventBooking',
        ),
    ]
