# Generated by Django 5.2.7 on 2025-11-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclstore', '0018_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='banners/videos/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
