# Generated by Django 5.2.7 on 2025-11-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclstore', '0019_banner_video_alter_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
