# Generated by Django 5.2.7 on 2025-12-07 03:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclstore', '0021_eventimage_eventvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='display_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Show this banner for X days (leave empty for unlimited).', null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cigaroffer',
            name='apply_to_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cigaroffer',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cigaroffer',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='drink',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
